name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build && npm run export

      - name: Move Output to `docs/`
        run: |
          rm -rf docs  # Clear old docs folder
          mv out docs  # Move static site to `docs/`

      - name: Commit and Push to `main`
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Deploy Next.js static site to GitHub Pages" || echo "No changes to commit"
          git push origin main
